apiVersion: v1
kind: ConfigMap
metadata:
  name: flink-proxy-config
data:
  jobmanagers: "2"
  name: jobmanager
  domain: jobmanager-headless.default.svc.cluster.local
  port: "8081"
  export.port.prefix: "3100" # exposed ports without last digit
---
apiVersion: v1
kind: Service
metadata:
  name: flink1
spec:
  ports:
    - port: 9400
      name: flink-dashboard1
      targetPort: 9400
      protocol: TCP
      nodePort: 31000
    - port: 9401
      name: flink-dashboard2
      targetPort: 9401
      protocol: TCP
      nodePort: 31001
    - port: 9402
      name: flink-dashboard3
      targetPort: 9402
      protocol: TCP
      nodePort: 31002
    - port: 9403
      name: flink-dashboard4
      targetPort: 9403
      protocol: TCP
      nodePort: 31003
    - port: 9404
      name: flink-dashboard5
      targetPort: 9404
      protocol: TCP
      nodePort: 31004
  selector:
    app: flink-nginx-proxy
  type: NodePort
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: flink-nginx-proxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: flink-nginx-proxy
    spec:
      volumes:
        - name: secret-volume
          secret:
            secretName: ssh-secret
      containers:
      - name: flink-nginx-proxy
        image: tma75/flink-nginx-proxy
        imagePullPolicy: Always
        env:
          - name: NBR_JOBMANAGERS
            valueFrom:
              configMapKeyRef:
                  name: flink-proxy-config
                  key: jobmanagers
          - name: NAME_JOBMANAGER
            valueFrom:
              configMapKeyRef:
                  name: flink-proxy-config
                  key: name
          - name: DOMAIN_JOBMANAGERS
            valueFrom:
              configMapKeyRef:
                  name: flink-proxy-config
                  key: domain
          - name: JOBMANAGER_PORT
            valueFrom:
              configMapKeyRef:
                  name: flink-proxy-config
                  key: port
          - name: EXPOSED_PORT_PREFIX
            valueFrom:
              configMapKeyRef:
                  name: flink-proxy-config
                  key: export.port.prefix
        volumeMounts:
          - mountPath: /etc/secrets/
            name: secret-volume
            readOnly: true
